const express = require("express");
const PDFDocument = require("pdfkit");
const ExcelJS = require("exceljs");
const db = require("../db");

function fmtRMB(n) { return "¥" + Number(n || 0).toLocaleString("en-US", { maximumFractionDigits: 2 }); }
function fmtIDR(n) { return "Rp " + Number(n || 0).toLocaleString("id-ID", { maximumFractionDigits: 0 }); }

module.exports = function () {
  const router = express.Router();

  // ---- PDF invoice for a Nadylan (Track A) order ----
  router.get("/order/:id/pdf", (req, res) => {
    const order = db.prepare("SELECT * FROM orders WHERE id=?").get(req.params.id);
    if (!order) return res.status(404).send("Order not found");

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename=invoice-order-${order.id}.pdf`);

    const doc = new PDFDocument({ margin: 50 });
    doc.pipe(res);

    doc.fontSize(20).fillColor("#1F3864").text("NEXUS — Nadylan Sourcing Invoice", { align: "left" });
    doc.moveDown(0.5);
    doc.fontSize(10).fillColor("#666").text(`Order #${order.id}  ·  ${order.created_at}  ·  Status: ${order.status}`);
    doc.moveDown(1);

    doc.fontSize(12).fillColor("#000").text(`Buyer: ${order.buyer_name}`);
    doc.text(`Product: ${order.product_summary || "-"}`);
    doc.text(`Exchange rate locked: ${order.fx_rate} IDR/RMB`);
    doc.moveDown(1);

    doc.fontSize(13).fillColor("#0F6E6E").text("Cost Breakdown");
    doc.moveDown(0.3);
    doc.fontSize(11).fillColor("#000");
    doc.text(`Product cost:        ${fmtRMB(order.product_cost)}`);
    doc.text(`Logistics cost:      ${fmtRMB(order.logistics_cost)}`);
    doc.text(`Service fee (${order.fee_pct}%):   ${fmtRMB(order.service_fee)}`);
    doc.moveDown(0.5);
    doc.fontSize(13).fillColor("#1F3864").text(`Total client payment: ${fmtRMB(order.total_payment)}`);
    doc.fontSize(11).fillColor("#1E8449").text(`Net profit: ${fmtRMB(order.net_profit)}`);

    doc.moveDown(2);
    doc.fontSize(9).fillColor("#999").text("Generated by NEXUS Ecosystem — Business Tracker", { align: "center" });

    doc.end();
  });

  // ---- PDF invoice for a Guangzhou Mate tour ----
  router.get("/tour/:id/pdf", (req, res) => {
    const tour = db.prepare("SELECT * FROM tours WHERE id=?").get(req.params.id);
    if (!tour) return res.status(404).send("Tour not found");

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename=invoice-tour-${tour.id}.pdf`);

    const doc = new PDFDocument({ margin: 50 });
    doc.pipe(res);

    doc.fontSize(20).fillColor("#1F3864").text("NEXUS — Guangzhou Mate Tour Invoice");
    doc.moveDown(0.5);
    doc.fontSize(10).fillColor("#666").text(`Tour #${tour.id}  ·  ${tour.created_at}  ·  Status: ${tour.status}`);
    doc.moveDown(1);

    doc.fontSize(12).fillColor("#000").text(`Package: ${tour.tier_name}`);
    doc.text(`Type: ${tour.tour_type === "bigbus" ? "Big Bus Group Tour" : "Private Tour"}`);
    doc.text(`Pax / Days: ${tour.pax_or_days}`);
    doc.moveDown(1);

    doc.fontSize(13).fillColor("#0F6E6E").text("Cost Breakdown");
    doc.fontSize(11).fillColor("#000");
    doc.text(`Total revenue: ${fmtIDR(tour.revenue)}`);
    doc.text(`Total cost:    ${fmtIDR(tour.cost)}`);
    doc.moveDown(0.5);
    doc.fontSize(13).fillColor("#1E8449").text(`Net margin: ${fmtIDR(tour.margin)}`);

    doc.moveDown(2);
    doc.fontSize(9).fillColor("#999").text("Generated by NEXUS Ecosystem — Business Tracker", { align: "center" });

    doc.end();
  });

  // ---- Excel export: all transactions ----
  router.get("/budget/transactions.xlsx", async (req, res) => {
    const rows = db.prepare("SELECT * FROM transactions ORDER BY created_at DESC").all();
    const wb = new ExcelJS.Workbook();
    const ws = wb.addWorksheet("Transactions");
    ws.columns = [
      { header: "Date", key: "created_at", width: 20 },
      { header: "Kind", key: "kind", width: 12 },
      { header: "Category", key: "category", width: 24 },
      { header: "Amount (RMB)", key: "amount_rmb", width: 16 },
      { header: "Source", key: "source", width: 14 },
      { header: "Note", key: "note", width: 40 },
    ];
    ws.getRow(1).font = { bold: true };
    rows.forEach((r) => ws.addRow(r));

    res.setHeader("Content-Type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
    res.setHeader("Content-Disposition", "attachment; filename=nexus-transactions.xlsx");
    await wb.xlsx.write(res);
    res.end();
  });

  // ---- Excel export: Nadylan orders ----
  router.get("/business/orders.xlsx", async (req, res) => {
    const rows = db.prepare("SELECT * FROM orders ORDER BY created_at DESC").all();
    const wb = new ExcelJS.Workbook();
    const ws = wb.addWorksheet("Orders");
    ws.columns = [
      { header: "Order #", key: "id", width: 10 },
      { header: "Buyer", key: "buyer_name", width: 22 },
      { header: "Product", key: "product_summary", width: 28 },
      { header: "Product Cost", key: "product_cost", width: 14 },
      { header: "Fee %", key: "fee_pct", width: 10 },
      { header: "Logistics", key: "logistics_cost", width: 14 },
      { header: "Total Payment", key: "total_payment", width: 16 },
      { header: "Net Profit", key: "net_profit", width: 14 },
      { header: "Status", key: "status", width: 12 },
      { header: "Date", key: "created_at", width: 20 },
    ];
    ws.getRow(1).font = { bold: true };
    rows.forEach((r) => ws.addRow(r));

    res.setHeader("Content-Type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
    res.setHeader("Content-Disposition", "attachment; filename=nexus-orders.xlsx");
    await wb.xlsx.write(res);
    res.end();
  });

  // ---- PDF: full budget report ----
  router.get("/budget/report.pdf", (req, res) => {
    const cfg = {};
    db.prepare("SELECT key, value FROM config").all().forEach((r) => (cfg[r.key] = r.value));
    const monthRows = db.prepare(`
      SELECT category, kind, COALESCE(SUM(amount_rmb),0) as total
      FROM transactions WHERE strftime('%Y-%m', created_at) = strftime('%Y-%m', 'now')
      GROUP BY category, kind
    `).all();

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", "attachment; filename=nexus-budget-report.pdf");

    const doc = new PDFDocument({ margin: 50 });
    doc.pipe(res);

    doc.fontSize(20).fillColor("#1F3864").text("NEXUS — Household Budget Report");
    doc.fontSize(10).fillColor("#666").text(`Generated: ${new Date().toISOString().slice(0, 10)}`);
    doc.moveDown(1);

    doc.fontSize(13).fillColor("#0F6E6E").text("This Month");
    doc.fontSize(11).fillColor("#000");
    monthRows.forEach((r) => {
      doc.text(`${r.category} (${r.kind}): ${fmtRMB(r.total)}`);
    });

    doc.moveDown(1);
    doc.fontSize(13).fillColor("#0F6E6E").text("Baseline Config");
    doc.fontSize(11).fillColor("#000");
    doc.text(`Monthly cap: ${fmtRMB(cfg.monthly_cap_rmb)}`);
    doc.text(`Living reserve: ${fmtRMB(cfg.living_reserve_rmb)}`);
    doc.text(`Revenue goal: ${fmtIDR(cfg.revenue_goal_idr)} by ${cfg.revenue_goal_deadline}`);

    doc.end();
  });

  return router;
};
